# Welcome to Jekyll!
# {{ site.title }}, {{ site.email }}, ..., {{ site.myvariable }}.
title: SITE TITLE
description: >-
  (V009 20190707) This is just following this tutorial by Mide Dane. Duh!
author: Mr. Y. Yoda
baseurl: "" 
url: "" 
email: site@ma.il
twitter_username: twitter
github_username:  webjekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
