title: Trying Jekyll at Giraffe Academy
description: >-
  (V042 20200808) I am just following Mike Dane's tutorial.
  It is a really really great tutorial!
author: "Mr. Yoda-Yoda"
theme: jekyll-theme-hacker
github: [metadata]

