title: Trying Giraffe Academy
description: >-
  (V017 20190714) This is just following the Giraffe Academy tutorial by Mide Dane.
author: Mr. Y. Yoda
baseurl: "" 
url: "" 
email: site@ma.il
twitter_username: twitter
github_username:  webjekyll

# Build settings
markdown: kramdown
theme: minima
github: [metadata]
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
