# Welcome to Jekyll!
# {{ site.title }}, {{ site.email }}, ..., {{ site.myvariable }}.
title: SITE TITLE
description: >-
  (V003 20190707) Site Discription
baseurl: "" 
url: "" 
email: site@ma.il
twitter_username: twitter
github_username:  github

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
