title: Trying Jekyll at Giraffe Academy
description: >-
  (V018 20190714) This is just following the Giraffe Academy tutorial by Mide Dane.
author: "Site Author"
baseurl: "" 
url: "" 
email: site@ma.il
twitter_username: twitter
github_username:  webjekyll

# Build settings
markdown: kramdown
theme: minima
github: [metadata]
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Default Page Author"

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
